apiVersion: v1
kind: PersistentVolume
metadata:
  name: vpn-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.7.40
    path: /data/kubernetes

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vpn-pvc
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

